# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/charlesvardeman/devcontainer-template',
                'doc_host': 'https://charlesvardeman.github.io',
                'git_url': 'https://github.com/charlesvardeman/charlesvardeman/devcontainer-template',
                'lib_path': 'charlesvardeman/devcontainer_template'},
  'syms': {'devcontainer_template.core': {'devcontainer_template.core.foo': ('core.html#foo', 'devcontainer_template/core.py')}}}
